import { Deal } from './types';

export const mockDeals: Deal[] = [
  {
    id: '1',
    title: '$100,000 in AWS Credits',
    partner: 'Amazon Web Services',
    description: 'Get up to $100,000 in AWS credits for your startup. Perfect for cloud infrastructure, storage, and compute needs.',
    fullDescription: 'Amazon Web Services is offering up to $100,000 in credits for eligible startups. These credits can be used across all AWS services including EC2, S3, Lambda, RDS, and more. This offer is designed to help early-stage startups build and scale their infrastructure without the immediate financial burden.',
    category: 'cloud',
    originalPrice: 100000,
    discountedPrice: 0,
    discountPercentage: 100,
    isLocked: true,
    requirements: ['Must be part of an accelerator program', 'Company less than 5 years old', 'Less than $5M in funding'],
    features: ['Access to all AWS services', 'Technical support included', 'Valid for 2 years', 'No credit card required'],
    logoUrl: 'https://images.pexels.com/photos/1181263/pexels-photo-1181263.jpeg?auto=compress&cs=tinysrgb&w=400',
    validUntil: '2024-12-31',
    claimCount: 234
  },
  {
    id: '2',
    title: '50% Off Notion Team Plan',
    partner: 'Notion',
    description: 'Get 50% off Notion Team plan for your first year. Unlimited blocks, unlimited team members.',
    fullDescription: 'Notion is the all-in-one workspace for your notes, tasks, wikis, and databases. With this exclusive offer, get 50% off the Team plan for your first year. Perfect for startup teams looking to centralize their documentation and project management.',
    category: 'productivity',
    originalPrice: 960,
    discountedPrice: 480,
    discountPercentage: 50,
    isLocked: false,
    requirements: ['Active startup with less than 50 employees', 'Valid email domain'],
    features: ['Unlimited blocks and file uploads', 'Collaborative workspace', 'Version history', 'Admin tools'],
    logoUrl: 'https://images.pexels.com/photos/4050315/pexels-photo-4050315.jpeg?auto=compress&cs=tinysrgb&w=400',
    validUntil: '2024-12-31',
    claimCount: 567
  },
  {
    id: '3',
    title: 'Free HubSpot CRM',
    partner: 'HubSpot',
    description: 'Get HubSpot CRM completely free forever. Includes contact management, email tracking, and meeting scheduling.',
    fullDescription: 'HubSpot CRM is free forever and comes packed with features to help you grow better. Track customer interactions, manage your pipeline, and automate your sales process. This is not a trial - it\'s completely free with no time limit.',
    category: 'marketing',
    originalPrice: 0,
    discountedPrice: 0,
    discountPercentage: 100,
    isLocked: false,
    requirements: ['Valid email address'],
    features: ['Contact management', 'Email tracking', 'Meeting scheduling', 'Live chat', 'Unlimited users'],
    logoUrl: 'https://images.pexels.com/photos/590022/pexels-photo-590022.jpeg?auto=compress&cs=tinysrgb&w=400',
    validUntil: '2025-12-31',
    claimCount: 1234
  },
  {
    id: '4',
    title: 'Figma Professional Free',
    partner: 'Figma',
    description: 'Get Figma Professional plan free for 1 year. Unlimited files, version history, and advanced prototyping.',
    fullDescription: 'Figma is the leading collaborative design tool. With this offer, get the Professional plan free for your first year, including unlimited files, version history, advanced prototyping, and team libraries. Perfect for design-focused startups.',
    category: 'design',
    originalPrice: 1440,
    discountedPrice: 0,
    discountPercentage: 100,
    isLocked: true,
    requirements: ['Design-focused startup', 'Less than 3 years old', 'Active product in development'],
    features: ['Unlimited files', 'Unlimited version history', 'Advanced prototyping', 'Team libraries', 'Design systems'],
    logoUrl: 'https://images.pexels.com/photos/196644/pexels-photo-196644.jpeg?auto=compress&cs=tinysrgb&w=400',
    validUntil: '2024-12-31',
    claimCount: 445
  },
  {
    id: '5',
    title: 'GitHub Enterprise Free',
    partner: 'GitHub',
    description: 'Get GitHub Enterprise free for 1 year. Advanced security, compliance, and deployment features.',
    fullDescription: 'GitHub Enterprise provides advanced security features, compliance tools, and deployment capabilities. This offer includes everything in GitHub Team plus SAML SSO, advanced auditing, and GitHub Advanced Security features.',
    category: 'development',
    originalPrice: 2520,
    discountedPrice: 0,
    discountPercentage: 100,
    isLocked: true,
    requirements: ['Active development team', 'Part of accelerator program', 'Less than $2M in funding'],
    features: ['SAML single sign-on', 'Advanced auditing', 'GitHub Advanced Security', 'Self-hosted runners', '50,000 CI/CD minutes'],
    logoUrl: 'https://images.pexels.com/photos/11035471/pexels-photo-11035471.jpeg?auto=compress&cs=tinysrgb&w=400',
    validUntil: '2024-12-31',
    claimCount: 332
  },
  {
    id: '6',
    title: 'Mixpanel Startup Program',
    partner: 'Mixpanel',
    description: 'Get $50,000 in Mixpanel credits. Advanced product analytics for your startup.',
    fullDescription: 'Mixpanel provides powerful product analytics to help you understand user behavior. With this offer, get $50,000 in credits to analyze your product data, create funnels, and track retention metrics.',
    category: 'analytics',
    originalPrice: 50000,
    discountedPrice: 0,
    discountPercentage: 100,
    isLocked: true,
    requirements: ['Pre-seed or seed stage', 'Less than $8M in total funding', 'Active product with users'],
    features: ['Unlimited data history', 'Unlimited reports', 'Group analytics', 'Data pipelines', 'Customer success support'],
    logoUrl: 'https://images.pexels.com/photos/669615/pexels-photo-669615.jpeg?auto=compress&cs=tinysrgb&w=400',
    validUntil: '2024-12-31',
    claimCount: 189
  },
  {
    id: '7',
    title: 'Mailchimp Essentials Free',
    partner: 'Mailchimp',
    description: 'Get Mailchimp Essentials free for 6 months. Email marketing and automation for your startup.',
    fullDescription: 'Mailchimp Essentials provides email marketing, automation, and basic reporting. This offer includes everything you need to start building your email list and engaging with customers.',
    category: 'marketing',
    originalPrice: 660,
    discountedPrice: 0,
    discountPercentage: 100,
    isLocked: false,
    requirements: ['Less than 50 employees', 'Active business'],
    features: ['10,000 contacts', 'Email automation', 'A/B testing', 'Custom branding', 'Basic reporting'],
    logoUrl: 'https://images.pexels.com/photos/1591062/pexels-photo-1591062.jpeg?auto=compress&cs=tinysrgb&w=400',
    validUntil: '2024-12-31',
    claimCount: 678
  },
  {
    id: '8',
    title: 'Stripe Atlas Package',
    partner: 'Stripe',
    description: 'Incorporate your startup with Stripe Atlas. Includes company formation, banking, and tax benefits.',
    fullDescription: 'Stripe Atlas helps you incorporate a company, open a US bank account, and start accepting payments globally. This comprehensive package includes legal formation, tax advisement, and banking setup.',
    category: 'productivity',
    originalPrice: 500,
    discountedPrice: 500,
    discountPercentage: 0,
    isLocked: false,
    requirements: ['First-time founders', 'Pre-incorporation'],
    features: ['Delaware C-Corp formation', 'IRS tax ID (EIN)', 'Bank account setup', 'Legal templates', 'Tax guidance'],
    logoUrl: 'https://images.pexels.com/photos/50987/money-card-business-credit-card-50987.jpeg?auto=compress&cs=tinysrgb&w=400',
    validUntil: '2025-12-31',
    claimCount: 423
  }
];
